services:
  customer-service:
    container_name: customer-service
    build: ./BankingSystem.Services.CustomerService
    image: csylverio/customer-service:latest
    ports:
      - "5001:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgresql
      - rabbitmq
    networks:
      - app-network

  account-service:
    container_name: account-service
    build: ./BankingSystem.Services.AccountService
    image: csylverio/account-service:latest
    ports:
      - "5002:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - app-network

  notification-worker:
    container_name: notification-worker
    build: ./BankingSystem.Services.NotificationWorker
    image: csylverio/notification-worker:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMQ__HostName: rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - app-network

  loan-service:
    container_name: loan-service
    build: ./BankingSystem.Services.LoanService
    image: csylverio/loan-service:latest
    ports:
      - "5003:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - app-network

  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 102030
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 102030
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: 102030
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
